# Generated by Django 6.0.1 on 2026-02-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Para el enlace #pizza, #hamburguesas, etc.', unique=True, verbose_name='Slug')),
                ('emoji', models.CharField(blank=True, help_text='Ej: 🍕 🍔', max_length=10, verbose_name='Emoji')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el menú', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(help_text='En pesos sin puntos ni coma', verbose_name='Precio')),
                ('image_url', models.URLField(blank=True, help_text='Enlace a la imagen del producto (ej: Unsplash, tu CDN)', verbose_name='URL de imagen')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Es promoción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro de la categoría', verbose_name='Orden')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
