# Generated by Django 5.2.9 on 2026-01-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('life_stage', models.CharField(choices=[('puppy', 'Puppy/Kitten'), ('adult', 'Adult'), ('senior', 'Senior'), ('all', 'All Stages')], default='all', max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='pets/products/')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pettype')),
            ],
        ),
    ]
