# Generated by Django 5.2.9 on 2026-01-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('alcohol_percentage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume in milliliters')),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='liquor/bottles/')),
                ('liquor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquor.liquortype')),
            ],
        ),
    ]
