# Generated by Django 5.2.9 on 2026-01-05 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('net_content', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit_measure', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('un', 'Unit'), ('lt', 'Liter')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_organic', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='market/products/')),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.aisle')),
            ],
        ),
    ]
